services:
    db:
        image: postgres:15-alpine
        container_name: fieldsync_inventory_db
        restart: always
        environment:
            POSTGRES_DB: fieldsync_inventory
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
            - ./init-schema:/docker-entrypoint-initdb.d
